### ISSUE TITLE
Migrate all apollo relate packages to 3.0

### ISSUE THREAD

**Issue by crisfcodes** [UnlyEd/next-right-now-admin#31]
https://github.com/UnlyEd/next-right-now-admin/blob/88b4be5da9e765e6550ae2b68dc4250979a5926b/package.json#L54

https://www.apollographql.com/docs/react/v3.0-beta/migrating/apollo-client-3-migration/

1. The Apollo Boost project is now retired, because Apollo Client 3.0 provides a similarly straightforward setup.

2. Includes functionality that previously required installing additional packages also includes numerous bug fixes and optimizations.

> WARNING: Apollo Client 3.0 is a major-version release that includes breaking changes. If you are updating an existing application to use Apollo Client 3.0, please see the changelog for details about these changes.

**Comment by Vadorequest** [comment]
Hi @cristian05 thanks for the heads-up.

This lib is not maintained as stated per https://github.com/UnlyEd/next-right-now-admin#status-stablepocnon-maintained

Also, the Apollo v3 support is still Beta version and I wouldn't include it until a proper release is made. Therefore, I have no intention of migrating to Apollo v3.
